2018-09-13 03:33:19 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected a dictionary. Got OrderedDict([('homeassistant', OrderedDict([('name', 'Home'), ('latitude', 34.051655), ('longitude', -118.389305), ('elevation', 87), ('unit_system', 'imperial'), ('time_zone', 'America/Los_Angeles'), ('customize', OrderedDict()), ('temperature_unit', 'F')])), ('introduction', {}), ('frontend', {}), ('config', {}), ('updater', {}), ('discovery', {}), ('conversation', {}), ('history', {}), ('logbook', {}), ('map', {}), ('sun', {}), ('sensor', [OrderedDict([('platform', 'yr')])]), ('tts', [Orde.... (See ?, line ?). Please check the docs at https://home-assistant.io/components/automation/
2018-09-13 03:33:31 WARNING (Thread-5) [netdisco.ssdp] Error fetching description at 192.168.0.10
2018-09-13 03:33:32 WARNING (Thread-5) [netdisco.ssdp] Error fetching description at http://192.168.0.21:8200/rootDesc.xml
2018-09-13 03:33:35 ERROR (MainThread) [homeassistant.components.device_tracker] Unable to load /home/homeassistant/.homeassistant/known_devices.yaml: Config file not found: /home/homeassistant/.homeassistant/known_devices.yaml
2018-09-13 03:39:02 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected a dictionary. Got OrderedDict([('homeassistant', OrderedDict([('name', 'Home'), ('latitude', 34.051655), ('longitude', -118.389305), ('elevation', 87), ('unit_system', 'imperial'), ('time_zone', 'America/Los_Angeles'), ('customize', OrderedDict()), ('temperature_unit', 'F')])), ('introduction', {}), ('frontend', {}), ('config', {}), ('updater', {}), ('discovery', {}), ('conversation', {}), ('history', {}), ('logbook', {}), ('map', {}), ('sun', {}), ('sensor', [OrderedDict([('platform', 'yr')])]), ('tts', [Orde.... (See ?, line ?). Please check the docs at https://home-assistant.io/components/automation/
2018-09-13 03:39:02 WARNING (MainThread) [homeassistant.components.group] remove:Group 'all_automations' doesn't exist!
